# Generated by Django 5.0.1 on 2024-01-08 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="social.address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="social_media_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="social.socialmedia",
            ),
        ),
    ]
