# Generated by Django 5.0.1 on 2024-01-12 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_address_id_alter_user_social_media_id'),
        ('social', '0002_address_user_alter_account_photo_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to='social.address'),
        ),
    ]
