# Generated by Django 5.0.1 on 2024-01-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_profile',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='photo_profile/'),
        ),
    ]
