# Generated by Django 5.0.1 on 2024-01-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_account_created_at_account_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='follower',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='posts_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
