# Generated by Django 5.0.1 on 2024-02-01 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_account_follower_account_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.account'),
        ),
    ]
