# Generated by Django 5.0.1 on 2024-02-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_socialmedia_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='follower',
            new_name='followers',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='account_id',
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
