# Generated by Django 5.0.1 on 2024-02-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_socialmedia_account_id_alter_platform_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountcontent',
            old_name='description',
            new_name='caption',
        ),
        migrations.AddField(
            model_name='accountcontent',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountcontent',
            name='comment_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountcontent',
            name='media_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
