# Generated by Django 5.0.1 on 2024-02-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_remove_accountcontent_comment_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentparent',
            old_name='account_content',
            new_name='content_code',
        ),
        migrations.AddField(
            model_name='accountcontent',
            name='content_code',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
