# Generated by Django 5.0.1 on 2024-02-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_rename_account_content_commentparent_content_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountcontent',
            old_name='like_count',
            new_name='likes_count',
        ),
        migrations.AddField(
            model_name='account',
            name='friends',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='likes_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='tweets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
