# Generated by Django 5.0.1 on 2024-02-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_rename_like_count_accountcontent_likes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reviews',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
